### ISSUE TITLE
snazzy --stdin doesn't work

### ISSUE THREAD

**Issue by lukechilds** [feross/snazzy#13]
`snazzy` is supposed to support all of `standard`'s options, however`--stdin` doesn't seem to work. If I echo in "fail" it should return `'fail' is not defined`.

```
$ echo fail | standard --stdin
standard: Use JavaScript Standard Style (http://standardjs.com)
  <text>:1:1: 'fail' is not defined.

$ echo fail | snazzy --stdin
fail
```

**Comment by feross** [comment]
Unfortunately, stdin is one thing that we can't easily support. The reason is that whenever `snazzy` sees stdin, it interprets that as unstyled output from `standard`. That's so that this usage can work:

```
standard --verbose | snazzy
```

It's not possible to tell which program is piping to `snazzy` so we can do something different if it's `echo` or another program that is not `standard`.

**Comment by lukechilds** [comment]
@feross What about if you check for the `--stdin` option? If it's set, treat stdin as code input, if not, treat stdin as `standard` output.

**Comment by feross** [comment]
We need to keep the `--stdin` option for some terminals where `process.stdin.isTTY` doesn't work reliably and it's needed to explicitly force stdin to be used.
