### ISSUE TITLE
Incompatible with standard 10

### ISSUE THREAD

**Issue by ghost** [feross/snazzy#16]
[demonstration repo](https://github.com/johnmuhl/fluffy-succotash)

To reproduce add `standard@beta` and `snazzy` to a project. Afterward running standard (standalone or via snazzy) will cause the error `Definition for rule 'standard/no-callback-literal' was not found`. Uninstalling snazzy or installing standard 9 fixes the issue.

**Comment by feross** [comment]
Snazzy includes a copy of `standard` 9.x and it sounds like somehow when you run `standard` an older version of `eslint-plugin-standard` is being used with a newer version of `eslint-config-standard` and so the 'standard/no-callback-literal' rule that is referenced is not available in the plugin.

When I run `rm -rf node_modules && npm install && npm run lint` it works for me. This may be a yarn issue. Do you see the same thing?

Also, once standard 10.0.0 is released (today), this issue will go away since the versions will be in sync again. So that's at least some consolation. :)

**Comment by ghost** [comment]
I'm sorry for the noise. You are right that it is a yarn issue.

**Comment by feross** [comment]
No problem!

**Comment by timothystewart6** [comment]
This is the top result when searching this error so I am posting this here in case someone else finds it.  If you have inconsistent versions of standard (9.x/10.x) (which is the case if you are using webpack 1.x with `standard-loader` 5.x and `standard` 10.x as your linter) you will also get this error.  Upgrading to webpack 2 is going to be the solution for me.
